// Seed data for the Ayodhya pilgrimage platform.
// `en` + `hi` are provided for key content; other languages fall back to `en` on the frontend.

const IMG = 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=70';
const TEMPLE_IMG = 'https://images.unsplash.com/photo-1609920658906-8223bd289001?auto=format&fit=crop&w=1200&q=70';

export const destinations = [
  {
    name: { en: 'Ayodhya', hi: 'अयोध्या' },
    state: 'Uttar Pradesh',
    shortDescription: {
      en: 'The birthplace of Lord Ram and home of the majestic Ram Mandir.',
      hi: 'भगवान राम की जन्मभूमि और भव्य राम मंदिर का घर।',
    },
    description: {
      en: 'Ayodhya, on the banks of the Sarayu river, is one of the seven sacred cities of Hinduism and the birthplace of Lord Ram. The newly consecrated Ram Mandir draws millions of devotees each year.',
      hi: 'सरयू नदी के तट पर बसी अयोध्या हिंदू धर्म के सात पवित्र शहरों में से एक है और भगवान राम की जन्मभूमि है।',
    },
    coverImage: IMG,
    gallery: [IMG, TEMPLE_IMG],
    location: { lat: 26.7922, lng: 82.1998, address: 'Ayodhya, Uttar Pradesh 224123' },
    highlights: ['Ram Mandir', 'Hanuman Garhi', 'Sarayu Ghat', 'Kanak Bhawan'],
    bestTimeToVisit: 'October to March',
    templeCount: 12,
    featured: true,
    rating: 4.9,
  },
  {
    name: { en: 'Varanasi', hi: 'वाराणसी' },
    state: 'Uttar Pradesh',
    shortDescription: { en: 'The spiritual capital of India on the banks of the Ganga.', hi: 'गंगा के तट पर भारत की आध्यात्मिक राजधानी।' },
    description: {
      en: 'Varanasi (Kashi) is among the oldest living cities in the world, famed for its ghats, the Kashi Vishwanath temple and the mesmerizing Ganga Aarti.',
      hi: 'वाराणसी (काशी) दुनिया के सबसे पुराने जीवित शहरों में से एक है, जो अपने घाटों और काशी विश्वनाथ मंदिर के लिए प्रसिद्ध है।',
    },
    coverImage: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=70',
    gallery: [],
    location: { lat: 25.3176, lng: 82.9739, address: 'Varanasi, Uttar Pradesh' },
    highlights: ['Kashi Vishwanath', 'Dashashwamedh Ghat', 'Ganga Aarti', 'Sarnath'],
    bestTimeToVisit: 'October to March',
    templeCount: 23,
    featured: true,
    rating: 4.8,
  },
  {
    name: { en: 'Prayagraj', hi: 'प्रयागराज' },
    state: 'Uttar Pradesh',
    shortDescription: { en: 'The holy confluence of the Ganga, Yamuna and Saraswati.', hi: 'गंगा, यमुना और सरस्वती का पवित्र संगम।' },
    description: { en: 'Prayagraj hosts the Triveni Sangam and the grand Kumbh Mela, the largest spiritual gathering on earth.', hi: 'प्रयागराज त्रिवेणी संगम और भव्य कुंभ मेले का आयोजन स्थल है।' },
    coverImage: 'https://images.unsplash.com/photo-1604608672516-f1b9b1d37076?auto=format&fit=crop&w=1200&q=70',
    location: { lat: 25.4358, lng: 81.8463, address: 'Prayagraj, Uttar Pradesh' },
    highlights: ['Triveni Sangam', 'Kumbh Mela', 'Anand Bhawan'],
    bestTimeToVisit: 'November to February',
    templeCount: 9,
    featured: true,
    rating: 4.7,
  },
  {
    name: { en: 'Naimisharanya', hi: 'नैमिषारण्य' },
    state: 'Uttar Pradesh',
    shortDescription: { en: 'The ancient forest where the Puranas were narrated.', hi: 'वह प्राचीन वन जहाँ पुराणों का वर्णन हुआ।' },
    description: { en: 'Naimisharanya is a revered tirtha where sages composed and recited the sacred Puranas.', hi: 'नैमिषारण्य एक पूजनीय तीर्थ है जहाँ ऋषियों ने पवित्र पुराणों की रचना की।' },
    coverImage: TEMPLE_IMG,
    location: { lat: 27.3496, lng: 80.4856, address: 'Naimisharanya, Sitapur, Uttar Pradesh' },
    highlights: ['Chakra Tirth', 'Lalita Devi Temple', 'Vyas Gaddi'],
    bestTimeToVisit: 'October to March',
    templeCount: 6,
    rating: 4.6,
  },
  {
    name: { en: 'Chitrakoot', hi: 'चित्रकूट' },
    state: 'Uttar Pradesh',
    shortDescription: { en: 'Where Lord Ram spent years of his exile.', hi: 'जहाँ भगवान राम ने वनवास के वर्ष बिताए।' },
    description: { en: 'Chitrakoot is a tranquil pilgrimage town associated with Lord Ram, Sita and Lakshman during their forest exile.', hi: 'चित्रकूट एक शांत तीर्थ नगरी है जो भगवान राम के वनवास से जुड़ी है।' },
    coverImage: IMG,
    location: { lat: 25.2, lng: 80.86, address: 'Chitrakoot, Uttar Pradesh' },
    highlights: ['Ramghat', 'Kamadgiri', 'Gupt Godavari'],
    bestTimeToVisit: 'October to March',
    templeCount: 7,
    rating: 4.6,
  },
  {
    name: { en: 'Mathura', hi: 'मथुरा' },
    state: 'Uttar Pradesh',
    shortDescription: { en: 'The birthplace of Lord Krishna.', hi: 'भगवान कृष्ण की जन्मभूमि।' },
    description: { en: 'Mathura, the birthplace of Lord Krishna, is a vibrant city of temples, festivals and the famous Janmabhoomi.', hi: 'भगवान कृष्ण की जन्मभूमि मथुरा मंदिरों और त्योहारों का जीवंत शहर है।' },
    coverImage: TEMPLE_IMG,
    location: { lat: 27.4924, lng: 77.6737, address: 'Mathura, Uttar Pradesh' },
    highlights: ['Krishna Janmabhoomi', 'Dwarkadhish Temple', 'Vishram Ghat'],
    bestTimeToVisit: 'October to March',
    templeCount: 15,
    featured: true,
    rating: 4.7,
  },
  {
    name: { en: 'Vrindavan', hi: 'वृंदावन' },
    state: 'Uttar Pradesh',
    shortDescription: { en: 'The playground of Lord Krishna, city of a thousand temples.', hi: 'भगवान कृष्ण की लीलाभूमि, हज़ार मंदिरों का शहर।' },
    description: { en: 'Vrindavan, where Krishna spent his childhood, is filled with temples, kirtans and devotion at every corner.', hi: 'वृंदावन, जहाँ कृष्ण ने अपना बचपन बिताया, मंदिरों और भक्ति से भरा हुआ है।' },
    coverImage: IMG,
    location: { lat: 27.5806, lng: 77.7006, address: 'Vrindavan, Uttar Pradesh' },
    highlights: ['Banke Bihari Temple', 'ISKCON', 'Prem Mandir', 'Nidhivan'],
    bestTimeToVisit: 'October to March',
    templeCount: 18,
    featured: true,
    rating: 4.8,
  },
];

export const temples = [
  {
    name: { en: 'Shri Ram Janmabhoomi Mandir', hi: 'श्री राम जन्मभूमि मंदिर' },
    destinationName: 'Ayodhya',
    category: 'Ram Temple',
    description: { en: 'The grand temple marking the birthplace of Lord Ram, built in the Nagara style.', hi: 'नागर शैली में निर्मित भगवान राम की जन्मभूमि का भव्य मंदिर।' },
    history: { en: 'Consecrated in January 2024, the temple stands at the revered Ram Janmabhoomi site after centuries of devotion.', hi: 'जनवरी 2024 में प्राण प्रतिष्ठित यह मंदिर सदियों की भक्ति के बाद राम जन्मभूमि स्थल पर खड़ा है।' },
    darshanTimings: '6:30 AM - 9:30 PM',
    aartiTimings: 'Mangala Aarti 4:00 AM, Shringar Aarti 6:15 AM, Sandhya Aarti 7:00 PM',
    dressCode: { en: 'Modest traditional attire recommended. Remove footwear before entry.', hi: 'सादे पारंपरिक वस्त्र पहनें। प्रवेश से पहले जूते उतारें।' },
    coverImage: TEMPLE_IMG,
    gallery: [TEMPLE_IMG, IMG],
    location: { lat: 26.7956, lng: 82.1943, address: 'Ram Janmabhoomi, Ayodhya' },
    nearbyAttractions: [
      { name: 'Hanuman Garhi', distance: '1.2 km' },
      { name: 'Kanak Bhawan', distance: '0.8 km' },
    ],
    featured: true,
  },
  {
    name: { en: 'Hanuman Garhi', hi: 'हनुमान गढ़ी' },
    destinationName: 'Ayodhya',
    category: 'Hanuman Temple',
    description: { en: 'A hilltop temple of Lord Hanuman, reached by climbing 76 steps.', hi: '76 सीढ़ियाँ चढ़कर पहुँचा जाने वाला भगवान हनुमान का पहाड़ी मंदिर।' },
    history: { en: 'A 10th-century temple believed to be where Hanuman resided to guard Ayodhya.', hi: '10वीं सदी का मंदिर, माना जाता है कि यहाँ हनुमान अयोध्या की रक्षा हेतु निवास करते थे।' },
    darshanTimings: '5:00 AM - 10:00 PM',
    aartiTimings: 'Morning 5:00 AM, Evening 9:00 PM',
    dressCode: { en: 'Traditional attire preferred.', hi: 'पारंपरिक वस्त्र पसंद किए जाते हैं।' },
    coverImage: IMG,
    location: { lat: 26.7969, lng: 82.2045, address: 'Hanuman Garhi, Ayodhya' },
    nearbyAttractions: [{ name: 'Ram Mandir', distance: '1.2 km' }],
    featured: true,
  },
  {
    name: { en: 'Kashi Vishwanath Temple', hi: 'काशी विश्वनाथ मंदिर' },
    destinationName: 'Varanasi',
    category: 'Shiva Temple',
    description: { en: 'One of the twelve Jyotirlingas, dedicated to Lord Shiva.', hi: 'भगवान शिव को समर्पित बारह ज्योतिर्लिंगों में से एक।' },
    history: { en: 'The temple has stood for centuries on the western bank of the Ganga and is central to Kashi’s spiritual life.', hi: 'यह मंदिर सदियों से गंगा के पश्चिमी तट पर स्थित है और काशी के आध्यात्मिक जीवन का केंद्र है।' },
    darshanTimings: '3:00 AM - 11:00 PM',
    aartiTimings: 'Mangala Aarti 3:00 AM, Sapta Rishi Aarti 7:00 PM',
    dressCode: { en: 'Modest attire; mobile phones restricted inside.', hi: 'सादे वस्त्र; अंदर मोबाइल फोन प्रतिबंधित।' },
    coverImage: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=70',
    location: { lat: 25.3109, lng: 83.0107, address: 'Lahori Tola, Varanasi' },
    nearbyAttractions: [{ name: 'Dashashwamedh Ghat', distance: '0.5 km' }],
    featured: true,
  },
];

export const packages = [
  {
    title: { en: 'Ayodhya Darshan', hi: 'अयोध्या दर्शन' },
    summary: { en: '2 days of soulful darshan at Ayodhya’s holiest temples.', hi: 'अयोध्या के पवित्रतम मंदिरों के 2 दिनों के दर्शन।' },
    description: { en: 'A curated 2-day pilgrimage covering Ram Mandir, Hanuman Garhi, Kanak Bhawan and a divine Sarayu aarti.', hi: 'राम मंदिर, हनुमान गढ़ी, कनक भवन और सरयू आरती को कवर करती 2 दिवसीय तीर्थयात्रा।' },
    destinationNames: ['Ayodhya'],
    durationDays: 2,
    durationNights: 1,
    price: 7999,
    discountPrice: 6499,
    coverImage: TEMPLE_IMG,
    gallery: [TEMPLE_IMG, IMG],
    inclusions: ['Hotel Stay (1 Night)', 'Daily Breakfast', 'AC Vehicle', 'Local Guide', 'All Sightseeing'],
    exclusions: ['Air/Train Fare', 'Personal Expenses', 'Lunch & Dinner', 'Entry Donations'],
    hotelInfo: { en: '3-star hotel near temple complex with breakfast.', hi: 'मंदिर परिसर के पास नाश्ते सहित 3-सितारा होटल।' },
    vehicleInfo: { en: 'Air-conditioned Sedan / SUV based on group size.', hi: 'समूह के आकार के अनुसार एसी सेडान / एसयूवी।' },
    itinerary: [
      { day: 1, title: { en: 'Arrival & Ram Mandir Darshan', hi: 'आगमन और राम मंदिर दर्शन' }, description: { en: 'Arrive in Ayodhya, check-in, visit Ram Janmabhoomi and evening Sarayu aarti.', hi: 'अयोध्या पहुँचें, चेक-इन करें, राम जन्मभूमि और संध्या सरयू आरती।' } },
      { day: 2, title: { en: 'Temple Tour & Departure', hi: 'मंदिर भ्रमण और प्रस्थान' }, description: { en: 'Hanuman Garhi, Kanak Bhawan, Nageshwarnath, then departure.', hi: 'हनुमान गढ़ी, कनक भवन, नागेश्वरनाथ, फिर प्रस्थान।' } },
    ],
    faq: [
      { question: { en: 'Is the Ram Mandir darshan included?', hi: 'क्या राम मंदिर दर्शन शामिल है?' }, answer: { en: 'Yes, guided darshan is included on Day 1.', hi: 'हाँ, पहले दिन निर्देशित दर्शन शामिल है।' } },
    ],
    rating: 4.9,
    reviewsCount: 214,
    featured: true,
    popular: true,
  },
  {
    title: { en: 'Ayodhya + Varanasi', hi: 'अयोध्या + वाराणसी' },
    summary: { en: '4-day twin-city pilgrimage of Ram and Shiva.', hi: 'राम और शिव की 4 दिवसीय युगल-नगरी तीर्थयात्रा।' },
    description: { en: 'Experience the divinity of Ayodhya and the ancient ghats of Varanasi in one seamless journey.', hi: 'एक ही यात्रा में अयोध्या की दिव्यता और वाराणसी के प्राचीन घाटों का अनुभव करें।' },
    destinationNames: ['Ayodhya', 'Varanasi'],
    durationDays: 4,
    durationNights: 3,
    price: 15999,
    discountPrice: 13999,
    coverImage: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=70',
    gallery: [IMG, TEMPLE_IMG],
    inclusions: ['Hotel Stay (3 Nights)', 'Daily Breakfast', 'AC Vehicle', 'Ganga Aarti', 'Local Guide'],
    exclusions: ['Air/Train Fare', 'Personal Expenses', 'Boat Ride Charges'],
    hotelInfo: { en: '3-star hotels in both cities.', hi: 'दोनों शहरों में 3-सितारा होटल।' },
    vehicleInfo: { en: 'AC SUV for intercity transfers.', hi: 'अंतरनगरीय यात्रा हेतु एसी एसयूवी।' },
    itinerary: [
      { day: 1, title: { en: 'Ayodhya Arrival', hi: 'अयोध्या आगमन' }, description: { en: 'Ram Mandir and Sarayu aarti.', hi: 'राम मंदिर और सरयू आरती।' } },
      { day: 2, title: { en: 'Ayodhya to Varanasi', hi: 'अयोध्या से वाराणसी' }, description: { en: 'Temple tour, drive to Varanasi.', hi: 'मंदिर भ्रमण, वाराणसी प्रस्थान।' } },
      { day: 3, title: { en: 'Kashi Vishwanath', hi: 'काशी विश्वनाथ' }, description: { en: 'Vishwanath darshan and evening Ganga aarti.', hi: 'विश्वनाथ दर्शन और संध्या गंगा आरती।' } },
      { day: 4, title: { en: 'Sarnath & Departure', hi: 'सारनाथ और प्रस्थान' }, description: { en: 'Morning boat ride, Sarnath, departure.', hi: 'प्रातः नौका विहार, सारनाथ, प्रस्थान।' } },
    ],
    faq: [],
    rating: 4.8,
    reviewsCount: 168,
    featured: true,
    popular: true,
  },
  {
    title: { en: 'Ayodhya + Prayagraj', hi: 'अयोध्या + प्रयागराज' },
    summary: { en: '3-day journey of Ram Janmabhoomi and Triveni Sangam.', hi: 'राम जन्मभूमि और त्रिवेणी संगम की 3 दिवसीय यात्रा।' },
    description: { en: 'Combine the darshan of Ayodhya with a holy dip at the Triveni Sangam in Prayagraj.', hi: 'अयोध्या के दर्शन को प्रयागराज में त्रिवेणी संगम के पवित्र स्नान के साथ जोड़ें।' },
    destinationNames: ['Ayodhya', 'Prayagraj'],
    durationDays: 3,
    durationNights: 2,
    price: 11999,
    discountPrice: 9999,
    coverImage: 'https://images.unsplash.com/photo-1604608672516-f1b9b1d37076?auto=format&fit=crop&w=1200&q=70',
    inclusions: ['Hotel Stay (2 Nights)', 'Daily Breakfast', 'AC Vehicle', 'Sangam Boat Ride'],
    exclusions: ['Air/Train Fare', 'Personal Expenses'],
    hotelInfo: { en: '3-star hotels.', hi: '3-सितारा होटल।' },
    vehicleInfo: { en: 'AC Sedan/SUV.', hi: 'एसी सेडान/एसयूवी।' },
    itinerary: [
      { day: 1, title: { en: 'Ayodhya Darshan', hi: 'अयोध्या दर्शन' }, description: { en: 'Ram Mandir & temples.', hi: 'राम मंदिर और मंदिर।' } },
      { day: 2, title: { en: 'Drive to Prayagraj', hi: 'प्रयागराज प्रस्थान' }, description: { en: 'Sangam visit and aarti.', hi: 'संगम भ्रमण और आरती।' } },
      { day: 3, title: { en: 'Sangam & Departure', hi: 'संगम और प्रस्थान' }, description: { en: 'Holy dip and departure.', hi: 'पवित्र स्नान और प्रस्थान।' } },
    ],
    faq: [],
    rating: 4.7,
    reviewsCount: 97,
    popular: true,
  },
  {
    title: { en: 'Ayodhya + Naimisharanya', hi: 'अयोध्या + नैमिषारण्य' },
    summary: { en: '3-day spiritual retreat to Ram’s city and the sages’ forest.', hi: 'राम की नगरी और ऋषियों के वन की 3 दिवसीय आध्यात्मिक यात्रा।' },
    description: { en: 'A peaceful pilgrimage combining Ayodhya with the ancient tirtha of Naimisharanya.', hi: 'अयोध्या को नैमिषारण्य के प्राचीन तीर्थ के साथ जोड़ती एक शांत तीर्थयात्रा।' },
    destinationNames: ['Ayodhya', 'Naimisharanya'],
    durationDays: 3,
    durationNights: 2,
    price: 10999,
    discountPrice: 8999,
    coverImage: TEMPLE_IMG,
    inclusions: ['Hotel Stay (2 Nights)', 'Daily Breakfast', 'AC Vehicle', 'Local Guide'],
    exclusions: ['Air/Train Fare', 'Personal Expenses'],
    hotelInfo: { en: '3-star hotels.', hi: '3-सितारा होटल।' },
    vehicleInfo: { en: 'AC Sedan/SUV.', hi: 'एसी सेडान/एसयूवी।' },
    itinerary: [
      { day: 1, title: { en: 'Ayodhya', hi: 'अयोध्या' }, description: { en: 'Temple darshan.', hi: 'मंदिर दर्शन।' } },
      { day: 2, title: { en: 'Naimisharanya', hi: 'नैमिषारण्य' }, description: { en: 'Chakra Tirth and Lalita Devi.', hi: 'चक्र तीर्थ और ललिता देवी।' } },
      { day: 3, title: { en: 'Departure', hi: 'प्रस्थान' }, description: { en: 'Morning darshan and return.', hi: 'प्रातः दर्शन और वापसी।' } },
    ],
    faq: [],
    rating: 4.6,
    reviewsCount: 54,
  },
];

export const hotels = [
  {
    name: 'Saryu Residency',
    destinationName: 'Ayodhya',
    description: { en: 'Comfortable 3-star stay minutes from Ram Mandir.', hi: 'राम मंदिर से कुछ मिनट की दूरी पर आरामदायक 3-सितारा ठहराव।' },
    coverImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=70',
    pricePerNight: 2499,
    rating: 4.5,
    starCategory: 3,
    amenities: ['Free WiFi', 'AC', 'Restaurant', 'Parking', 'Room Service'],
    address: 'Near Ram Path, Ayodhya',
    featured: true,
  },
  {
    name: 'Ram Heritage Hotel',
    destinationName: 'Ayodhya',
    description: { en: 'Premium 4-star hotel with rooftop temple views.', hi: 'छत से मंदिर दृश्य वाला प्रीमियम 4-सितारा होटल।' },
    coverImage: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=70',
    pricePerNight: 4999,
    rating: 4.7,
    starCategory: 4,
    amenities: ['Free WiFi', 'AC', 'Restaurant', 'Gym', 'Parking', 'Spa'],
    address: 'Civil Lines, Ayodhya',
    featured: true,
  },
  {
    name: 'Ganga View Guest House',
    destinationName: 'Varanasi',
    description: { en: 'Budget-friendly stay overlooking the ghats.', hi: 'घाटों के सामने किफायती ठहराव।' },
    coverImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=70',
    pricePerNight: 1799,
    rating: 4.3,
    starCategory: 2,
    amenities: ['Free WiFi', 'AC', 'Cafe', 'Ghat View'],
    address: 'Assi Ghat, Varanasi',
  },
];

export const cabs = [
  {
    vehicleType: 'Sedan',
    name: 'Toyota Etios / Dzire',
    seats: 4,
    pricePerKm: 12,
    baseFare: 500,
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=900&q=70',
    features: ['AC', 'Music System', '2 Luggage'],
  },
  {
    vehicleType: 'SUV',
    name: 'Toyota Innova Crysta',
    seats: 7,
    pricePerKm: 18,
    baseFare: 800,
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=900&q=70',
    features: ['AC', 'Music System', '4 Luggage', 'Extra Legroom'],
  },
  {
    vehicleType: 'Luxury',
    name: 'Mercedes E-Class',
    seats: 4,
    pricePerKm: 45,
    baseFare: 2500,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=70',
    features: ['Premium AC', 'Leather Seats', 'Chauffeur', 'Refreshments'],
  },
];

export const blogs = [
  {
    title: { en: 'A Complete Guide to Ram Mandir Darshan in 2026', hi: '2026 में राम मंदिर दर्शन की संपूर्ण गाइड' },
    excerpt: { en: 'Everything you need to know — timings, dress code, online passes and travel tips.', hi: 'समय, ड्रेस कोड, ऑनलाइन पास और यात्रा सुझाव — सब कुछ जानें।' },
    content: { en: 'The Ram Mandir in Ayodhya welcomes millions of devotees. Plan your darshan with the right timings, book your passes online, and dress modestly. Reach early to avoid queues...', hi: 'अयोध्या का राम मंदिर लाखों श्रद्धालुओं का स्वागत करता है। सही समय के साथ अपने दर्शन की योजना बनाएं...' },
    coverImage: TEMPLE_IMG,
    category: 'Pilgrimage',
    tags: ['Ayodhya', 'Ram Mandir', 'Darshan', 'Travel Guide'],
    readTime: 6,
    metaTitle: 'Ram Mandir Darshan Guide 2026 | Timings & Tips',
    metaDescription: 'Plan your Ram Mandir darshan in Ayodhya — timings, dress code, online passes and travel tips.',
  },
  {
    title: { en: 'Top 7 Temples to Visit in Ayodhya', hi: 'अयोध्या में घूमने योग्य शीर्ष 7 मंदिर' },
    excerpt: { en: 'Beyond Ram Mandir — discover the hidden spiritual gems of Ayodhya.', hi: 'राम मंदिर से परे — अयोध्या के छिपे आध्यात्मिक रत्न खोजें।' },
    content: { en: 'From Hanuman Garhi to Kanak Bhawan and Nageshwarnath, Ayodhya is dotted with sacred sites...', hi: 'हनुमान गढ़ी से कनक भवन और नागेश्वरनाथ तक, अयोध्या पवित्र स्थलों से भरी है...' },
    coverImage: IMG,
    category: 'Temples',
    tags: ['Ayodhya', 'Temples', 'Hanuman Garhi'],
    readTime: 5,
  },
  {
    title: { en: 'Experiencing the Ganga Aarti in Varanasi', hi: 'वाराणसी में गंगा आरती का अनुभव' },
    excerpt: { en: 'A sensory journey through the most divine ritual on the ghats.', hi: 'घाटों पर सबसे दिव्य अनुष्ठान की एक यात्रा।' },
    content: { en: 'Every evening, the Dashashwamedh Ghat comes alive with lamps, chants and devotion during the Ganga Aarti...', hi: 'हर शाम, गंगा आरती के दौरान दशाश्वमेध घाट दीपों और मंत्रों से जीवंत हो उठता है...' },
    coverImage: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=70',
    category: 'Experiences',
    tags: ['Varanasi', 'Ganga Aarti', 'Ghats'],
    readTime: 4,
  },
];

export const galleryItems = [
  { title: 'Ram Mandir at Dawn', type: 'image', category: 'Temples', url: TEMPLE_IMG, thumbnail: TEMPLE_IMG, featured: true },
  { title: 'Sarayu Ghat Aarti', type: 'image', category: 'Aarti', url: IMG, thumbnail: IMG, featured: true },
  { title: 'Ganga Aarti, Varanasi', type: 'image', category: 'Ghats', url: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=70' },
  { title: 'Triveni Sangam', type: 'image', category: 'Nature', url: 'https://images.unsplash.com/photo-1604608672516-f1b9b1d37076?auto=format&fit=crop&w=1200&q=70' },
  { title: 'Temple Festival', type: 'image', category: 'Festivals', url: IMG },
  { title: 'Pilgrims at Hanuman Garhi', type: 'image', category: 'Pilgrims', url: TEMPLE_IMG },
];

export const testimonials = [
  { name: 'Rohit Sharma', location: 'Delhi', rating: 5, message: 'The Ayodhya Darshan package was perfectly organized. The guide was knowledgeable and the hotel was excellent.' },
  { name: 'Priya Patel', location: 'Ahmedabad', rating: 5, message: 'Booking in Gujarati made it so easy for my parents. A truly divine experience from start to finish.' },
  { name: 'Anil Deshmukh', location: 'Pune', rating: 4, message: 'Smooth cab service and timely darshan arrangements. Highly recommend for family trips.' },
  { name: 'Lakshmi Iyer', location: 'Chennai', rating: 5, message: 'Loved the Ayodhya + Varanasi tour. Everything from boat rides to aarti was well managed.' },
];
